"""
Data-driven item & tile registry.
Single source of truth for all items, tiles, recipes, placeables, NPCs.
Both server and client read from this.
"""

# ══════════════════════════════════════════════════════════════════
#  MATERIAL MODIFIERS — scale stats for items made from each material
# ══════════════════════════════════════════════════════════════════

MATERIALS = {
    "wood":   {"hp_mult": 0.5, "capacity_mult": 0.5, "speed_mult": 1.0,  "cost_base": 5,  "color": [139,107,58]},
    "stone":  {"hp_mult": 1.0, "capacity_mult": 0.75,"speed_mult": 0.9,  "cost_base": 8,  "color": [95,95,90]},
    "copper": {"hp_mult": 1.5, "capacity_mult": 1.0, "speed_mult": 1.0,  "cost_base": 10, "color": [184,115,51]},
    "iron":   {"hp_mult": 2.0, "capacity_mult": 1.5, "speed_mult": 0.85, "cost_base": 12, "color": [130,140,155]},
}

# Base stats for generated items
CHEST_BASE_HP = 20
CHEST_BASE_CAPACITY = 50

# ══════════════════════════════════════════════════════════════════
#  TILES — terrain and structures
# ══════════════════════════════════════════════════════════════════

TILES = {
    # Natural terrain (generated by noise)
    0:  {"name": "deep_water",  "label": "Deep Water",   "solid": True,  "speed": 1.0, "color": [18,32,62]},
    1:  {"name": "water",       "label": "Water",        "solid": True,  "speed": 1.0, "color": [34,62,102]},
    2:  {"name": "sand",        "label": "Sand",         "solid": False, "speed": 0.7, "color": [194,178,128]},
    3:  {"name": "dirt",        "label": "Dirt",         "solid": False, "speed": 1.0, "color": [90,65,38]},
    4:  {"name": "alien_grass", "label": "Alien Grass",  "solid": False, "speed": 1.0, "color": [42,88,48]},
    5:  {"name": "rock",        "label": "Rock",         "solid": False, "speed": 0.85,"color": [95,95,90]},
    6:  {"name": "dense_rock",  "label": "Dense Rock",   "solid": True,  "speed": 1.0, "color": [58,56,54]},
    7:  {"name": "ore_iron",    "label": "Iron Ore",     "solid": False, "speed": 1.0, "color": [139,94,60]},
    8:  {"name": "ore_copper",  "label": "Copper Ore",   "solid": False, "speed": 1.0, "color": [184,115,51]},
    9:  {"name": "alien_flora", "label": "Alien Flora",  "solid": False, "speed": 1.0, "color": [42,170,90]},
    10: {"name": "crystal",     "label": "Crystal",      "solid": False, "speed": 1.0, "color": [136,204,238]},
    11: {"name": "alien_tree",  "label": "Alien Tree",   "solid": True,  "speed": 1.0, "color": [30,90,45]},
    # Player structures
    100: {"name": "wall",       "label": "Stone Wall",   "solid": True,  "speed": 1.0, "color": [72,72,82]},
    101: {"name": "floor",      "label": "Stone Path",   "solid": False, "speed": 1.15,"color": [100,100,110]},
    102: {"name": "sign",       "label": "Sign",         "solid": False, "speed": 1.0, "color": [140,110,60]},
    # Machines
    200: {"name": "miner",        "label": "Auto-Miner",   "solid": True,  "speed": 1.0, "color": [204,136,51]},
    201: {"name": "fabricator",   "label": "Fabricator",    "solid": True,  "speed": 1.0, "color": [102,136,204]},
    202: {"name": "storage",      "label": "Storage Crate", "solid": True, "speed": 1.0, "color": [136,102,68]},
    203: {"name": "furnace",      "label": "Furnace",      "solid": True,  "speed": 1.0, "color": [204,68,34]},
    # Chests (machine types)
    204: {"name": "wood_chest",   "label": "Wood Chest",   "solid": True, "speed": 1.0, "color": [139,107,58]},
    205: {"name": "stone_chest",  "label": "Stone Chest",  "solid": True, "speed": 1.0, "color": [95,95,90]},
    206: {"name": "copper_chest", "label": "Copper Chest", "solid": True, "speed": 1.0, "color": [184,115,51]},
    207: {"name": "iron_chest",   "label": "Iron Chest",   "solid": True, "speed": 1.0, "color": [130,140,155]},
}

# ══════════════════════════════════════════════════════════════════
#  MINABLE — what you get from mining tiles
# ══════════════════════════════════════════════════════════════════

MINABLE = {
    # tile_id: {item, drop, time, hp, respawn (0=never)}
    5:  {"item": "stone",      "drop": 2, "time": 1.5, "hp": 5,  "respawn": 300},
    6:  {"item": "stone",      "drop": 3, "time": 2.5, "hp": 10, "respawn": 300},
    7:  {"item": "iron_ore",   "drop": 2, "time": 2.0, "hp": 15, "respawn": 300},
    8:  {"item": "copper_ore", "drop": 2, "time": 2.0, "hp": 15, "respawn": 300},
    9:  {"item": "biomass",    "drop": 2, "time": 1.0, "hp": 3,  "respawn": 120},
    10: {"item": "crystal",    "drop": 1, "time": 2.5, "hp": 8,  "respawn": 600},
    11: {"item": "wood",       "drop": 3, "time": 2.0, "hp": 8,  "respawn": 180},
    100:{"item": "stone",      "drop": 1, "time": 1.0, "hp": 1,  "respawn": 0},
}

# ══════════════════════════════════════════════════════════════════
#  ITEMS — all inventory items (resources, crafted, placeable)
# ══════════════════════════════════════════════════════════════════

ITEMS = {
    # Raw resources
    "stone":       {"label": "Stone",       "color": "#888888", "category": "resource"},
    "iron_ore":    {"label": "Iron Ore",    "color": "#8b5e3c", "category": "resource"},
    "copper_ore":  {"label": "Copper Ore",  "color": "#b87333", "category": "resource"},
    "crystal":     {"label": "Crystal",     "color": "#88ccee", "category": "resource"},
    "biomass":     {"label": "Biomass",     "color": "#2aaa5a", "category": "resource"},
    "wood":        {"label": "Wood",        "color": "#8b6b3a", "category": "resource"},
    # Processed
    "iron_plate":  {"label": "Iron Plate",  "color": "#aaaacc", "category": "processed"},
    "copper_plate":{"label": "Copper Plate","color": "#ddaa66", "category": "processed"},
    "iron_gear":   {"label": "Iron Gear",   "color": "#8899aa", "category": "processed"},
    "circuit":     {"label": "Circuit",     "color": "#44cc88", "category": "processed"},
    "wall_block":  {"label": "Wall Block",  "color": "#666677", "category": "processed"},
    # Placeable (crafted then placed in world)
    "stone_wall":  {
        "label": "Stone Wall", "color": "#555566", "category": "placeable",
        "placeable": {"build_key": "wall", "tile_id": 100, "passable": False},
    },
    "stone_path":  {
        "label": "Stone Path", "color": "#777788", "category": "placeable",
        "placeable": {"build_key": "floor", "tile_id": 101, "passable": True},
    },
    "sign": {
        "label": "Sign", "color": "#8c6e3c", "category": "placeable",
        "placeable": {"build_key": "sign", "tile_id": 102, "passable": True, "has_text": True},
    },
    # Chests (crafted items — placed via machine system)
    "wood_chest":   {"label": "Wood Chest",   "color": "#8b6b3a", "category": "machine_item", "machine_type": 204},
    "stone_chest":  {"label": "Stone Chest",  "color": "#5f5f5a", "category": "machine_item", "machine_type": 205},
    "copper_chest": {"label": "Copper Chest", "color": "#b87333", "category": "machine_item", "machine_type": 206},
    "iron_chest":   {"label": "Iron Chest",   "color": "#8299aa", "category": "machine_item", "machine_type": 207},
    # Land claim
    "claim_flag": {
        "label": "Claim Flag", "color": "#44cc44", "category": "special",
    },
    # Craftable machines
    "stone_furnace": {
        "label": "Stone Furnace", "color": "#cc4422", "category": "placeable",
        "placeable": {"build_key": "furnace_place", "tile_id": 203, "passable": False},
    },
}

# ══════════════════════════════════════════════════════════════════
#  HAND RECIPES — crafting without a machine
# ══════════════════════════════════════════════════════════════════

HAND_RECIPES = {
    "stone_wall": {"cost": {"stone": 3}, "qty": 1, "research": "stone_walls"},
    "stone_path": {"cost": {"stone": 1}, "qty": 1, "research": "stone_paths"},
    "sign":          {"cost": {"wood": 2}, "qty": 1},
    "claim_flag":    {"cost": {"wood": 10, "stone": 10}, "qty": 1, "research": "homestead"},
    "wood_chest":    {"cost": {"wood": 5}, "qty": 1, "research": "stone_tools"},
    "stone_chest":   {"cost": {"stone": 8}, "qty": 1, "research": "stone_tools"},
    "copper_chest":  {"cost": {"copper_plate": 10}, "qty": 1, "research": "smelting"},
    "iron_chest":    {"cost": {"iron_plate": 12}, "qty": 1, "research": "smelting"},
    "stone_furnace": {"cost": {"stone": 15}, "qty": 1, "research": "smelting"},
}

# ══════════════════════════════════════════════════════════════════
#  MACHINE RECIPES — crafting via machine
# ══════════════════════════════════════════════════════════════════

MACHINE_RECIPES = {
    "iron_plate":  {"inputs": {"iron_ore": 2},                  "time": 3.0, "machine": 203},
    "copper_plate":{"inputs": {"copper_ore": 2},                "time": 3.0, "machine": 203},
    "iron_gear":   {"inputs": {"iron_plate": 2},                "time": 2.0, "machine": 201},
    "circuit":     {"inputs": {"copper_plate": 1, "iron_plate": 1}, "time": 4.0, "machine": 201},
    "wall_block":  {"inputs": {"stone": 5},                     "time": 2.0, "machine": 201},
}

# ══════════════════════════════════════════════════════════════════
#  MACHINES — placeable machines
# ══════════════════════════════════════════════════════════════════

MACHINES = {
    200: {"name": "Auto-Miner",    "cost": {"stone": 5, "iron_ore": 3}},
    201: {"name": "Fabricator",    "cost": {"stone": 8, "iron_plate": 4}},
    202: {"name": "Storage Crate", "cost": {"stone": 4}},
    203: {"name": "Furnace",       "cost": {"stone": 10}},
    # Chests — cost is 1 crafted chest item, capacity from material modifiers
    204: {"name": "Wood Chest",    "cost": {"wood_chest": 1},   "max_storage": int(CHEST_BASE_CAPACITY * MATERIALS["wood"]["capacity_mult"])},
    205: {"name": "Stone Chest",   "cost": {"stone_chest": 1},  "max_storage": int(CHEST_BASE_CAPACITY * MATERIALS["stone"]["capacity_mult"])},
    206: {"name": "Copper Chest",  "cost": {"copper_chest": 1}, "max_storage": int(CHEST_BASE_CAPACITY * MATERIALS["copper"]["capacity_mult"])},
    207: {"name": "Iron Chest",    "cost": {"iron_chest": 1},   "max_storage": int(CHEST_BASE_CAPACITY * MATERIALS["iron"]["capacity_mult"])},
}

# ══════════════════════════════════════════════════════════════════
#  BUILDABLE — what the server accepts for "build" messages
#  Auto-generated from ITEMS with placeable flag
# ══════════════════════════════════════════════════════════════════

BUILDABLE = {}
for _item_key, _item in ITEMS.items():
    if "placeable" in _item:
        p = _item["placeable"]
        BUILDABLE[p["build_key"]] = {
            "tile_id": p["tile_id"],
            "cost": {_item_key: 1},  # costs 1 of the crafted item
            "passable": p["passable"],
        }

# ══════════════════════════════════════════════════════════════════
#  NPC ANIMALS
# ══════════════════════════════════════════════════════════════════

ANIMALS = {
    "sheep": {
        "name": "Sheep",
        "max_hp": 20,
        "speed": 30,
        "spawn_tiles": [4, 9],
        "wander_radius": 3,
        "wander_pause": [2, 6],
        "color": "#ddddcc",
    },
}

# ══════════════════════════════════════════════════════════════════
#  CRAFTING MENU — categories for the client UI
# ══════════════════════════════════════════════════════════════════

CRAFTING_MENU = [
    {
        "title": "STRUCTURES",
        "color": "#7788aa",
        "items": [
            {"name": "Stone Wall",  "craft_id": "stone_wall",  "cost": {"stone": 3}, "note": "Blocks movement"},
            {"name": "Stone Path",  "craft_id": "stone_path",  "cost": {"stone": 1}, "note": "+15% speed"},
            {"name": "Sign",        "craft_id": "sign",        "cost": {"wood": 2},  "note": "Place text in world"},
            {"name": "Claim Flag", "craft_id": "claim_flag",  "cost": {"wood": 10, "stone": 10}, "note": "Claim 25x25 land"},
        ],
    },
    {
        "title": "STORAGE",
        "color": "#886644",
        "items": [
            {"name": "Wood Chest",   "craft_id": "wood_chest",   "cost": {"wood": 5},           "note": "25 slots"},
            {"name": "Stone Chest",  "craft_id": "stone_chest",  "cost": {"stone": 8},          "note": "37 slots"},
            {"name": "Copper Chest", "craft_id": "copper_chest", "cost": {"copper_plate": 10},  "note": "50 slots"},
            {"name": "Iron Chest",   "craft_id": "iron_chest",   "cost": {"iron_plate": 12},    "note": "75 slots"},
        ],
    },
    {
        "title": "MACHINES",
        "color": "#cc8833",
        "items": [
            {"name": "Stone Furnace", "craft_id": "stone_furnace", "cost": {"stone": 15}, "note": "Smelts ore"},
            {"name": "Auto-Miner",    "machine_type": 200, "cost": {"stone": 5, "iron_ore": 3}},
            {"name": "Fabricator",    "machine_type": 201, "cost": {"stone": 8, "iron_plate": 4}},
            {"name": "Storage Crate", "machine_type": 202, "cost": {"stone": 4}},
        ],
    },
    {
        "title": "SMELTING (Furnace)",
        "color": "#cc4422",
        "items": [
            {"name": "Iron Plate",  "cost": {"iron_ore": 2},   "machine": True},
            {"name": "Copper Plate","cost": {"copper_ore": 2},  "machine": True},
        ],
    },
    {
        "title": "CRAFTING (Fabricator)",
        "color": "#6688cc",
        "items": [
            {"name": "Iron Gear", "cost": {"iron_plate": 2},                     "machine": True},
            {"name": "Circuit",   "cost": {"copper_plate": 1, "iron_plate": 1},  "machine": True},
            {"name": "Wall Block","cost": {"stone": 5},                           "machine": True},
        ],
    },
]

# ══════════════════════════════════════════════════════════════════
#  ZONES — world area definitions
# ══════════════════════════════════════════════════════════════════

TILE_PX = 32
CHUNK_SIZE = 64
# Spawn point in world pixel coordinates
SPAWN_X = CHUNK_SIZE * TILE_PX * 0.5  # center of chunk 0,0
SPAWN_Y = CHUNK_SIZE * TILE_PX * 0.5
# Spawn zone: 50x50 tiles centered on spawn
SPAWN_ZONE_RADIUS = 25  # tiles from center

ZONES = {
    "spawn": {
        "name": "Spawn Point",
        "center_x": SPAWN_X / TILE_PX,  # in tile coords
        "center_y": SPAWN_Y / TILE_PX,
        "radius": SPAWN_ZONE_RADIUS,
        "admin_only": True,
        "color": "#44aa66",
    },
}


CLAIM_RADIUS = 12  # 25x25 = radius 12 from center

# Active claims loaded from DB at runtime — populated by main.py
_active_claims: list[dict] = []

def set_active_claims(claims: list[dict]):
    global _active_claims
    _active_claims = claims

def get_zone_at(tile_x: int, tile_y: int) -> dict:
    """Returns the zone info for a tile position, checking spawn + player claims."""
    # Check spawn zone first
    for zone_id, zone in ZONES.items():
        dx = abs(tile_x - zone["center_x"])
        dy = abs(tile_y - zone["center_y"])
        if dx <= zone["radius"] and dy <= zone["radius"]:
            return {"id": zone_id, **zone}

    # Check player claims
    for claim in _active_claims:
        dx = abs(tile_x - claim["center_x"])
        dy = abs(tile_y - claim["center_y"])
        if dx <= CLAIM_RADIUS and dy <= CLAIM_RADIUS:
            return {
                "id": f"claim_{claim['id']}",
                "name": claim["name"],
                "owner_id": claim["user_id"],
                "admin_only": False,
                "claimed": True,
                "color": "#44cc44",
            }

    return {"id": "wilds", "name": "The Wilds", "admin_only": False, "color": "#888888"}


# ══════════════════════════════════════════════════════════════════
#  HELPER — generate client init data bundle
# ══════════════════════════════════════════════════════════════════

def get_client_registry() -> dict:
    """Returns the full registry for the client init message."""
    return {
        "tiles": {str(k): v for k, v in TILES.items()},
        "items": ITEMS,
        "minable": {str(k): v for k, v in MINABLE.items()},
        "handRecipes": HAND_RECIPES,
        "machineRecipes": MACHINE_RECIPES,
        "machines": {str(k): v for k, v in MACHINES.items()},
        "buildable": {k: v for k, v in BUILDABLE.items()},
        "craftingMenu": CRAFTING_MENU,
        "animals": ANIMALS,
        "materials": MATERIALS,
        "zones": ZONES,
        "spawnX": SPAWN_X,
        "spawnY": SPAWN_Y,
        "tileSpeeds": {str(k): v["speed"] for k, v in TILES.items() if v["speed"] != 1.0},
    }
